web:
  image: 'gitlab/gitlab-ce:latest'
  container_name: gitlab
  restart: always
  hostname: 'example.com'
  environment:
    VIRTUAL_HOST: example.com
    LETSENCRYPT_HOST: example.com
    LETSENCRYPT_EMAIL: contact@example.com
    GITLAB_OMNIBUS_CONFIG: |
      #external_url 'https://git.labict.be'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '80'
    - '443'
    - '22:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab'
    - '/srv/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/data:/var/opt/gitlab'
